import * as LucideIcons from 'lucide-react'
import { LucideIcon } from 'lucide-react'

// Map icon name strings to Lucide icon components
// Only including icons that are actually used in the codebase or commonly needed
const iconMap: Record<string, LucideIcon> = {
  // Common icons used in the codebase
  Code: LucideIcons.Code,
  Database: LucideIcons.Database,
  Server: LucideIcons.Server,
  Network: LucideIcons.Network,
  Cloud: LucideIcons.Cloud,
  Zap: LucideIcons.Zap,
  Shield: LucideIcons.Shield,
  Building2: LucideIcons.Building2,
  Heart: LucideIcons.Heart,
  ShoppingCart: LucideIcons.ShoppingCart,
  Truck: LucideIcons.Truck,
  Home: LucideIcons.Home,
  Users: LucideIcons.Users,
  CheckCircle: LucideIcons.CheckCircle,
  Rocket: LucideIcons.Rocket,
  Target: LucideIcons.Target,
  FileText: LucideIcons.FileText,
  CreditCard: LucideIcons.CreditCard,
  Wallet: LucideIcons.Wallet,
  DollarSign: LucideIcons.DollarSign,
  TrendingUp: LucideIcons.TrendingUp,
  BarChart: LucideIcons.BarChart,
  Layers: LucideIcons.Layers,
  Globe: LucideIcons.Globe,
  Smartphone: LucideIcons.Smartphone,
  Monitor: LucideIcons.Monitor,
  Palette: LucideIcons.Palette,
  Search: LucideIcons.Search,
  Mail: LucideIcons.Mail,
  Phone: LucideIcons.Phone,
  Calendar: LucideIcons.Calendar,
  ArrowRight: LucideIcons.ArrowRight,
  Settings: LucideIcons.Settings,
  Wrench: LucideIcons.Wrench,
  Cog: LucideIcons.Cog,
  Box: LucideIcons.Box,
  Package: LucideIcons.Package,
  Store: LucideIcons.Store,
  Factory: LucideIcons.Factory,
  Car: LucideIcons.Car,
  Plane: LucideIcons.Plane,
  Hotel: LucideIcons.Hotel,
  GraduationCap: LucideIcons.GraduationCap,
  Book: LucideIcons.Book,
  Stethoscope: LucideIcons.Stethoscope,
  Activity: LucideIcons.Activity,
  BarChart2: LucideIcons.BarChart2,
  PieChart: LucideIcons.PieChart,
  LineChart: LucideIcons.LineChart,
  TrendingDown: LucideIcons.TrendingDown,
  Lightbulb: LucideIcons.Lightbulb,
  Star: LucideIcons.Star,
  Award: LucideIcons.Award,
  ThumbsUp: LucideIcons.ThumbsUp,
  MessageSquare: LucideIcons.MessageSquare,
  Bell: LucideIcons.Bell,
  Lock: LucideIcons.Lock,
  Unlock: LucideIcons.Unlock,
  Eye: LucideIcons.Eye,
  EyeOff: LucideIcons.EyeOff,
  User: LucideIcons.User,
  UserPlus: LucideIcons.UserPlus,
  Users2: LucideIcons.Users2,
  Briefcase: LucideIcons.Briefcase,
  Folder: LucideIcons.Folder,
  File: LucideIcons.File,
  Image: LucideIcons.Image,
  Video: LucideIcons.Video,
  Music: LucideIcons.Music,
  Download: LucideIcons.Download,
  Upload: LucideIcons.Upload,
  Share: LucideIcons.Share,
  Link: LucideIcons.Link,
  ExternalLink: LucideIcons.ExternalLink,
  Copy: LucideIcons.Copy,
  Edit: LucideIcons.Edit,
  Trash: LucideIcons.Trash,
  Plus: LucideIcons.Plus,
  Minus: LucideIcons.Minus,
  X: LucideIcons.X,
  Check: LucideIcons.Check,
  AlertCircle: LucideIcons.AlertCircle,
  Info: LucideIcons.Info,
  HelpCircle: LucideIcons.HelpCircle,
  ChevronRight: LucideIcons.ChevronRight,
  ChevronLeft: LucideIcons.ChevronLeft,
  ChevronUp: LucideIcons.ChevronUp,
  ChevronDown: LucideIcons.ChevronDown,
  ArrowUp: LucideIcons.ArrowUp,
  ArrowDown: LucideIcons.ArrowDown,
  ArrowLeft: LucideIcons.ArrowLeft,
  Play: LucideIcons.Play,
  Pause: LucideIcons.Pause,
  SkipForward: LucideIcons.SkipForward,
  SkipBack: LucideIcons.SkipBack,
  Repeat: LucideIcons.Repeat,
  Shuffle: LucideIcons.Shuffle,
  Volume: LucideIcons.Volume,
  Volume2: LucideIcons.Volume2,
  VolumeX: LucideIcons.VolumeX,
  Mic: LucideIcons.Mic,
  MicOff: LucideIcons.MicOff,
  Camera: LucideIcons.Camera,
  CameraOff: LucideIcons.CameraOff,
  Map: LucideIcons.Map,
  MapPin: LucideIcons.MapPin,
  Navigation: LucideIcons.Navigation,
  Compass: LucideIcons.Compass,
  Flag: LucideIcons.Flag,
  Tag: LucideIcons.Tag,
  Tags: LucideIcons.Tags,
  Filter: LucideIcons.Filter,
  Sliders: LucideIcons.Sliders,
  Grid: LucideIcons.Grid,
  List: LucideIcons.List,
  Layout: LucideIcons.Layout,
  Columns: LucideIcons.Columns,
  Rows: LucideIcons.Rows,
  Maximize: LucideIcons.Maximize,
  Minimize: LucideIcons.Minimize,
  Maximize2: LucideIcons.Maximize2,
  Minimize2: LucideIcons.Minimize2,
  Move: LucideIcons.Move,
  RotateCw: LucideIcons.RotateCw,
  RotateCcw: LucideIcons.RotateCcw,
  RefreshCw: LucideIcons.RefreshCw,
  RefreshCcw: LucideIcons.RefreshCcw,
  Power: LucideIcons.Power,
  Battery: LucideIcons.Battery,
  BatteryCharging: LucideIcons.BatteryCharging,
  Wifi: LucideIcons.Wifi,
  WifiOff: LucideIcons.WifiOff,
  Signal: LucideIcons.Signal,
  SignalLow: LucideIcons.SignalLow,
  SignalMedium: LucideIcons.SignalMedium,
  SignalHigh: LucideIcons.SignalHigh,
  Bluetooth: LucideIcons.Bluetooth,
  BluetoothOff: LucideIcons.BluetoothOff,
  Radio: LucideIcons.Radio,
  Tv: LucideIcons.Tv,
  MonitorSpeaker: LucideIcons.MonitorSpeaker,
  Printer: LucideIcons.Printer,
  HardDrive: LucideIcons.HardDrive,
  Disc: LucideIcons.Disc,
  Cpu: LucideIcons.Cpu,
  MemoryStick: LucideIcons.MemoryStick,
  Mouse: LucideIcons.Mouse,
  Keyboard: LucideIcons.Keyboard,
  Headphones: LucideIcons.Headphones,
  Speaker: LucideIcons.Speaker,
  FileCode: LucideIcons.FileCode,
}

/**
 * Get a Lucide icon component by name
 * @param iconName - The name of the icon (e.g., 'Code', 'Database')
 * @returns The icon component or undefined if not found
 */
export function getIconComponent(iconName: string): LucideIcon | undefined {
  // First check the iconMap
  if (iconMap[iconName]) {
    return iconMap[iconName]
  }
  
  // Then try to access from LucideIcons directly (safely)
  try {
    const icon = (LucideIcons as unknown as Record<string, LucideIcon>)[iconName]
    if (icon && typeof icon === 'function') {
      return icon
    }
  } catch (error) {
    // Icon doesn't exist, return undefined
  }
  
  return undefined
}

